### ISSUE TITLE
Current NuGet package doesn't work

### ISSUE THREAD

**Issue by bobasaurus** [predictionmachines/SDSlite#20] opened 2020-11-13 21:13 UTC
I've tried to install and use the latest SDSlite NuGet package (1.4.3) a few times, but it doesn't seem to make the Microsoft.Research namespace available.  Typing "using Microsoft." doesn't have an option for "Research" in the intellisense popup, and trying to convert code that used the older full-system installed version of Microsoft Scientific DataSet shows this error on compile:

Error CS0234 The type or namespace name 'Research' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

I have the latest NetCDF4 C libs installed, and use them frequently in other projects.  I'm using Microsoft Visual Studio Community 2019 Preview, Version 16.9.0 Preview 1.0.  Windows 10 x64.

**Comment by vassilyl** [comment] 2020-11-14 06:14
What is target framework of the project you reference sdslite from?

**Comment by bobasaurus** [comment] 2020-11-15 20:29
.NET Framework 4.7.2.  

I've installed and used many other nuget packages without issue, this is the first one to fail like this.

**Comment by vassilyl** [comment] 2020-11-16 08:55
I can reproduce the issue, thank you. Most likely that is because of improper framework monikers in the nupkg. Fixed in the latest NuGet package version 1.4.4.

**Closed by vassilyl** 2020-11-16 08:55 UTC

**Comment by bobasaurus** [comment] 2020-11-19 01:04
This seems to have fixed it, thanks a lot.
